#!/usr/bin/env bash

# shell into the remote instance and install node/nginx/pm2

cd ~/.ssh
ssh -T -i $key ubuntu@ec2-54-185-228-130.us-west-2.compute.amazonaws.com << 'ENDSSH'
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm i -g pm2 -y
sudo apt install postgresql postgresql-contrib -y
sudo apt-get -y install nginx
exit

ENDSSH
